name:                haskellrt
version:             0.1.0.0
github:              "githubuser/haskellrt"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskellrt#readme>

dependencies:
- base >= 4.7 && < 5
- tasty >= 1.4.2.3 

library:
  source-dirs: src

executables:
  haskellrt-exe:
    main:                Main.hs
    extra-libraries:
    - cryptolib
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellrt

tests:
  haskellrt-test:
    main:                Spec.hs
    source-dirs:         test
    extra-libraries:
    - cryptolib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellrt
