name: Haskell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runner-job:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up Haskell
      uses: actions/setup-haskell@v1.1
      with:
         ghc-version: 'latest'
         enable-stack: true
         stack-version: 'latest'

    - name: Test
      run:
        ./bin/colonies dev; stack test 
