name: Haskell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runner-job:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    # TODO: There is an error in the Haskell Github action 

    # If this is unexpected, please check if version 8.10.1 is pre-installed.
    # The list of pre-installed versions is available here: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
    # The above list follows a common haskell convention that the three latest major releases of ghc are commonly supported.
    # If the list is outdated, please file an issue here: https://github.com/actions/virtual-environments
    # by using the appropriate tool request template: https://github.com/actions/virtual-environments/issues/new/choose
    # Attempting to install ghc 8.10.1 using apt-get
    # /usr/bin/sudo -- sh -c apt-get -y install ghc-8.10.1
    # Reading package lists...
    # Building dependency tree...
    # Reading state information...
    # E: Unable to locate package ghc-8.10.1
    # E: Couldn't find any package by glob 'ghc-8.10.1'
    # E: Couldn't find any package by regex 'ghc-8.10.1'
    # - name: Set up Haskell
    #   uses: actions/setup-haskell@v1.1
    #   with:
    #      ghc-version: 'latest'
    #      enable-stack: true
    #      stack-version: 'latest'

    - name: Test
      run:
        #./bin/colonies dev; stack test 
        echo 
