name: Haskell

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runner-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up Haskell
      uses: actions/setup-haskell@v1.1
      with:
         ghc-version: '8.10.7'
         enable-stack: true
         stack-version: '2.7.5'

    - name: Test
      run: | 
        echo
        stack version
